#!/usr/bin/env bash

SCALE=830
WP_CONFIG_PATH="$HOME/.config/wm/wallpapers.conf"

if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    dmenu="bemenu"
else
    dmenu="dmenu"
fi

configure_wallpaper_menu(){
    monitors="$(monitors_info.sh -m)"
    monitors_index="$(monitors_info.sh -m | nl --starting-line-number=0)"
    selected_monitor="$(echo "$monitors" | $dmenu)"
    exit_if_none $selected_monitor

    selected_index="$(echo "$monitors_index" | grep "$selected_monitor" | awk '{print $1}')"

    dimension="$(monitors_info.sh -od | head -n $selected_index | awk 'BEGIN {FS="x"} {print $1}')"

    resize_hint=$(echo "$dimension" | awk '{s+=$1} END {printf "%.0f\n", s}')

    file_location="$(crop_img "$selected_index" "$selected_index" "Center" $resize_hint)"

    exit_if_none $file_location

    like_it="$(echo -e "yes\nno" | $dmenu -p "Wanna set the image as wallpaper?")"

    if [ "$like_it" == "yes" ]; then
        set_wallpaper "${selected_index}" "$file_location"
    fi
}

exit_if_none(){
    local valor="$1"

    if [ -z "${valor}" ]; then
        exit 0
    fi
}

convert_file(){
    filename="$(basename $file)"
    convert $file /tmp/${filename}.jpg
    sxiv /tmp/${filename}.jpg &
    #convert ${file} ${file}.jpg
}

reverse_file(){
    filename="$(basename $file)"
    convert $file /tmp/${filename}.png
    sxiv /tmp/${filename}.png &
    #convert ${file} ${file}.jpg
}

save_img(){
    local theme="$(printf "day\nnight\nshabbat" | $dmenu -p "Choose the theme")"
    exit_if_none "${theme}"

    #local mode="$(printf "\nultra\ndual" | $dmenu -p "Choose the modality")"

    local save_location="$HOME/Documents/Pictures/Wallpapers/dual/$theme/"
    cp ${file} "${save_location}"

    notify-send "Wallpaper saved" "Saved to ${save_location}"
}

resize_img_plus(){
    filename="$(basename $file)"
    temp_file="rec_$filename"

    local htop=$(monitors_info.sh -d | awk 'BEGIN {FS="x"} {if ($2 > TESTE) TESTE=$2;} END {print TESTE}')
    local overriden_htop=$(monitors_info.sh -od | awk 'BEGIN {FS="x"} {if ($2 > TESTE) TESTE=$2;} END {print TESTE}')
    local ltop=$(monitors_info.sh -d | awk 'BEGIN {FS="x"; TESTE=10000} {if ($2 < TESTE) TESTE=$2;} END {print TESTE}')
    local htoppls=$(monitors_info.sh -d | awk -v SCALE=$SCALE 'BEGIN {FS="x"} {if ($2 > TESTE) TESTE=$2;} END {print TESTE+SCALE}')
    local optimal_rescale="$(monitors_info.sh -D)x${htop}"
    local overriden_optimal_rescale="$(monitors_info.sh -oD)x${overriden_htop}"
    local optimal_rescale_ppls="$(echo $(monitors_info.sh -D) + $SCALE | bc)x${htoppls}"
    local low_optimal_rescale="$(monitors_info.sh -D)x${ltop}"

    local img_dimensions=$(identify ${file} | grep -Eo "[[:digit:]]+ *x *[[:digit:]]+" | head -n 1)
    local width_img_dimensions=$(identify ${file} | grep -Eo "[[:digit:]]+ *x *[[:digit:]]+" | head -n 1 | cut -d 'x' -f 1)
    local sum=$(echo $(monitors_info.sh -D)+${htop} | bc)

    local half_img="$((width_img_dimensions + ${sum}))x$((width_img_dimensions + ${sum}))"

    direction="$(printf "Center\nSouth\nNorth\nWest\nEast\nNorthWest\nSouthWest\nNorthEast\nSouthEast\nForget\nNone" | $dmenu -p "Choose the direction")"
    exit_if_none "$direction"

    local resolutions=$(monitors_info.sh -d)
    imgsize="$(printf "445x805\n${optimal_rescale}\n${overriden_optimal_rescale}\n${optimal_rescale_ppls}\n${low_optimal_rescale}\n${resolutions}\n${half_img}" | $dmenu -p "Choose the dimension")"
    exit_if_none "$imgsize"

    vadjust="$(printf "+0\n+65\n+100\n+200\n+300" | $dmenu -p "Set the vertical adjustment")"
    hadjust="$(printf "+0\n+65\n+100\n+200\n+300" | $dmenu -p "Set the horizontal adjustment")"

    convert "$file" -quality 100 -resize "${imgsize}"^ -gravity ${direction} -extent "${imgsize}${hadjust}${vadjust}" "/tmp/$temp_file"

    sxiv /tmp/$temp_file &
}

crop_img(){
    monitor=$(monitors_info.sh -n "$1")
    index="$2"
    gravity="$3"
    resize_hint="$4"

    direction="$(printf "West\nCenter\nSouth\nNorth\nEast\nNorthWest\nSouthWest\nNorthEast\nSouthEast\nForget\nNone" | $dmenu -p "Choose the direction")"
    exit_if_none "${direction}"
    resize="$(printf "+0\n+65\n+100\n+200\n+300" | $dmenu -p "Set the vertical deviation")"
    if [ -z "${resize_hint}"]; then
        horizontal="$(printf "+0\n-100\n+100\n+200\n+300\n+1080" | $dmenu -p "Set the horizontal deviation")"
    else
        horizontal="$(printf "+${resize_hint}\n+0\n-100\n+100\n+200\n+300" | $dmenu -p "Set the horizontal deviation")"
    fi

    filename="$(basename $file)"

    temp_file="/tmp/tmp_$filename"

    local override="$(printf "Yes\nNo" | $dmenu -p "Override the scale?")"
    if [ "${override}" == "Yes" ]; then
        rescale_dim="$(monitors_info.sh -oD)x$(monitors_info.sh -od "${monitor}" | awk 'BEGIN {FS="x"}; {print $2}')"
    else
        rescale_dim="$(monitors_info.sh -D)x$(monitors_info.sh -d "${monitor}" | awk 'BEGIN {FS="x"}; {print $2}')"
    fi

    xvalue="$(monitors_info.sh -d "${monitor}" | awk 'BEGIN {FS="x"}; {print $1}')"
    yvalue="$(monitors_info.sh -d "${monitor}" | awk 'BEGIN {FS="x"}; {print $2}')"

    convert "$file" -filter Triangle -quality 100 -gravity ${direction} -resize "${rescale_dim}"^ -extent "${rescale_dim}${horizontal}${resize}" "${temp_file}"

    # Resize to the choosen monitor
    file_location="/tmp/crp_${index}_${filename}"
    convert "${temp_file}" -quality 100 -filter Triangle -resize ${xvalue}x${yvalue}^ -gravity ${direction} -extent "${xvalue}x${yvalue}" "${file_location}"
    sxiv "${file_location}"&

    echo "${file_location}"
    #nitrogen --head=${index} --save --set-scaled "${file_location}"
}

recort_img(){
    monitor=$(monitors_info.sh -m | (printf "Custom\n" && cat) | $dmenu -p "Choose the monitor to base the image")
    index="$monitor"

    direction="$(printf "Center\nSouth\nNorth\nWest\nEast\nNorthWest\nSouthWest\nNorthEast\nSouthEast\nForget\nNone" | $dmenu -p "Choose the direction")"
    resize="$(printf "+0\n+65\n+100\n+200\n+300" | $dmenu -p "Set the vertical deviation")"
    horizontal="$(printf "+0\n-100\n+100\n+200\n+300\n+1080" | $dmenu -p "Set the horizontal deviation")"
    
    filename="$(basename $file)"

    if [ "${monitor}" == "Custom" ]; then
        monitor_info="$(printf "2000x2000" | $dmenu -p "Set the dimension")"
    else
        monitor_info="$(monitors_info.sh -d "${monitor}")"
    fi

    xvalue="$(echo $monitor_info | awk 'BEGIN {FS="x"}; {print $1}')"
    yvalue="$(echo $monitor_info | awk 'BEGIN {FS="x"}; {print $2}')"

    # Resize to the choosen monitor
    file_location="/tmp/crp_${index}_${filename}"
    convert "${file}" -quality 100 -filter Triangle -gravity ${direction} -extent "${xvalue}x${yvalue}${horizontal}${resize}" -resize ${xvalue}x${yvalue}^ "${file_location}"
    sxiv "${file_location}"&
}

set_wallpaper(){
    local monitor="$1"
    local file_name="$2"

    if [ -z "${file_name}" ]; then
        file_name="${file}"
    fi


    if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
        echo "Wayland. Doing nothing"
        if [ -z "$(pgrep swww-daemon)" ]; then
            # Init the daemon if not runnint
            swww init
        fi
        swww img -o $(monitors_info.sh -n $monitor) "$file_name" --transition-type wave --transition-step 15 --transition-fps 120

    else
        nitrogen --head=${monitor} --save --set-scaled --random "$file_name"
    fi
    sed -i "s#$monitor:.*#$monitor:$file_name#g" $WP_CONFIG_PATH
}

while read file
do
    case "$1" in
        "C-c")
            convert_file ;;
        "C-C")
            reverse_file ;;
        "C-w")
            nitrogen --save --set-zoom-fill "$file" ;;
        "C-e")
            recort_img "1" "1" "East";;
        "C-r")
            resize_img_plus "$file";;
        "C-t")
            crop_img "0" "0" "Center";;
        "C-y")
            crop_img "1" "1" "Center";;
        "C-u")
            crop_img "2" "2" "Center";;
        "C-i")
            configure_wallpaper_menu "${file}";;
        "C-g")
            convert -rotate 90 "$file" "$file" ;;
        "C-i")
            convert -flop "$file" "$file";;
        "C-s")
            save_img;;
        "C-l")
            cp "$file" $HOME/Documents/Pictures/lock.png ;;
        "C-0")
            set_wallpaper "0";;
        "C-1")
            set_wallpaper "1";;
        "C-2")
            set_wallpaper "2";;
        "C-a")
            rm "$file" ;;
        "C-z")
            convert "$file" $file.png 
            sxiv $file.png&;;
        "C-n")
            tag=$(echo "Entre a tag" | dmenu)
            /home/alexvanaxe/Documents/Projects/bn/generator/image_tagger.sh "$(basename $file .png)" "$tag";;
        "C-b")
            nome=$(echo "Entre o nome" | dmenu)
            tag=$(echo "Entre a tag" | dmenu)
            /home/alexvanaxe/Documents/Projects/bn/generator/image_tagger.sh "$nome" "$tag"
            #cp "$file" ~/zCEDHarley/Images/Nexus/SFW/Harley/${nome}.png;;
            cp "$file" ~/teste/${nome}.png;;

        "C-p")
            basename ${file} .png | xclip -i -selection clipboard;;
    esac
done
