#!/usr/bin/env sh

# TR_TORRENT_DIR

chmod -R 770 "$TR_TORRENT_DIR/$TR_TORRENT_NAME"
mv "$TR_TORRENT_DIR/$TR_TORRENT_NAME" /home/media/Movies/
chgrp -R plex /home/media/Movies/*

notify-send "Torrent finished" "Movie torrent added to the plex."
