# manage.py help
complete -f -c manage.py -a "changepassword"
complete -f -c manage.py -a "createsuperuser"

complete -f -c manage.py -a "remove_stale_contenttypes"

complete -f -c manage.py -a "check"
complete -f -c manage.py -a "compilemessages"
complete -f -c manage.py -a "createcachetable"
complete -f -c manage.py -a "dbshell"
complete -f -c manage.py -a "diffsettings"
complete -f -c manage.py -a "dumpdata"
complete -f -c manage.py -a "flush"
complete -f -c manage.py -a "inspectdb"
complete -f -c manage.py -a "loaddata"
complete -f -c manage.py -a "makemessages"
complete -f -c manage.py -a "makemigrations"
complete -f -c manage.py -a "migrate"
complete -f -c manage.py -a "sendtestemail"
complete -f -c manage.py -a "shell"
complete -f -c manage.py -a "showmigrations"
complete -f -c manage.py -a "sqlflush"
complete -f -c manage.py -a "sqlmigrate"
complete -f -c manage.py -a "sqlsequencereset"
complete -f -c manage.py -a "squashmigrations"
complete -f -c manage.py -a "startapp"
complete -f -c manage.py -a "startproject"
complete -f -c manage.py -a "test"
complete -f -c manage.py -a "testserver"

complete -f -c manage.py -a "admin_generator"
complete -f -c manage.py -a "clean_pyc"
complete -f -c manage.py -a "clear_cache"
complete -f -c manage.py -a "compile_pyc"
complete -f -c manage.py -a "create_command"
complete -f -c manage.py -a "create_jobs"
complete -f -c manage.py -a "create_template_tags"
complete -f -c manage.py -a "delete_squashed_migrations"
complete -f -c manage.py -a "describe_form"
complete -f -c manage.py -a "drop_test_database"
complete -f -c manage.py -a "dumpscript"
complete -f -c manage.py -a "export_emails"
complete -f -c manage.py -a "find_template"
complete -f -c manage.py -a "generate_password"
complete -f -c manage.py -a "generate_secret_key"
complete -f -c manage.py -a "graph_models"
complete -f -c manage.py -a "mail_debug"
complete -f -c manage.py -a "merge_model_instances"
complete -f -c manage.py -a "notes"
complete -f -c manage.py -a "passwd"
complete -f -c manage.py -a "pipchecker"
complete -f -c manage.py -a "print_settings"
complete -f -c manage.py -a "print_user_for_session"
complete -f -c manage.py -a "reset_db"
complete -f -c manage.py -a "reset_schema"
complete -f -c manage.py -a "runjob"
complete -f -c manage.py -a "runjobs"
complete -f -c manage.py -a "runprofileserver"
complete -f -c manage.py -a "runscript"
complete -f -c manage.py -a "runserver_plus"
complete -f -c manage.py -a "set_default_site"
complete -f -c manage.py -a "set_fake_emails"
complete -f -c manage.py -a "set_fake_passwords"
complete -f -c manage.py -a "shell_plus"
complete -f -c manage.py -a "show_template_tags"
complete -f -c manage.py -a "show_templatetags"
complete -f -c manage.py -a "show_urls"
complete -f -c manage.py -a "sqlcreate"
complete -f -c manage.py -a "sqldiff"
complete -f -c manage.py -a "sqldsn"
complete -f -c manage.py -a "sync_s3"
complete -f -c manage.py -a "syncdata"
complete -f -c manage.py -a "unreferenced_files"
complete -f -c manage.py -a "update_permissions"
complete -f -c manage.py -a "validate_templates"

complete -f -c manage.py -a "cleartokens"
complete -f -c manage.py -a "createapplication"

complete -f -c manage.py -a "fixoperations"
complete -f -c manage.py -a "resetdatabase"

complete -f -c manage.py -a "generateschema"

complete -f -c manage.py -a "clearsessions"

complete -f -c manage.py -a "collectstatic"
complete -f -c manage.py -a "findstatic"
complete -f -c manage.py -a "runserver"
