# manage.py help
complete -f -c manage.py -n "__fish_use_subcommand auth" -a "auth"
complete -f -c manage.py -n "__fish_seen_subcommand_from auth" -a "changepassword"
complete -f -c manage.py -n "__fish_seen_subcommand_from auth" -a "createsuperuser"

complete -f -c manage.py -a "contenttypes"
complete -f -c manage.py -n "__fish_seen_subcommand_from contenttypes" -a "remove_stale_contenttypes"

complete -f -c manage.py -n "__fish_use_subcommand django" -a "django"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "check"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "compilemessages"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "createcachetable"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "dbshell"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "diffsettings"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "dumpdata"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "flush"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "inspectdb"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "loaddata"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "makemessages"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "makemigrations"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "migrate"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "sendtestemail"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "shell"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "showmigrations"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "sqlflush"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "sqlmigrate"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "sqlsequencereset"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "squashmigrations"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "startapp"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "startproject"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "test"
complete -f -c manage.py -n "__fish_seen_subcommand_from django" -a "testserver"

complete -f -c manage.py -n "__fish_use_subcommand django_extensions" -a "django_extensions"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "admin_generator"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "clean_pyc"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "clear_cache"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "compile_pyc"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "create_command"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "create_jobs"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "create_template_tags"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "delete_squashed_migrations"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "describe_form"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "drop_test_database"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "dumpscript"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "export_emails"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "find_template"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "generate_password"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "generate_secret_key"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "graph_models"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "mail_debug"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "merge_model_instances"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "notes"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "passwd"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "pipchecker"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "print_settings"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "print_user_for_session"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "reset_db"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "reset_schema"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "runjob"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "runjobs"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "runprofileserver"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "runscript"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "runserver_plus"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "set_default_site"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "set_fake_emails"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "set_fake_passwords"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "shell_plus"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "show_template_tags"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "show_templatetags"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "show_urls"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "sqlcreate"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "sqldiff"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "sqldsn"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "sync_s3"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "syncdata"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "unreferenced_files"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "update_permissions"
complete -f -c manage.py -n "__fish_seen_subcommand_from django_extensions" -a "validate_templates"

complete -f -c manage.py -n "__fish_use_subcommand auth2_provider" -a "oauth2_provider"
complete -f -c manage.py -n "__fish_seen_subcommand_from auth2_provider" -a "cleartokens"
complete -f -c manage.py -n "__fish_seen_subcommand_from auth2_provider" -a "createapplication"

complete -f -c manage.py -n "__fish_use_subcommand operation" -a "operation"
complete -f -c manage.py -n "__fish_seen_subcommand_from operation" -a "fixoperations"
complete -f -c manage.py -n "__fish_seen_subcommand_from operation" -a "resetdatabase"

complete -f -c manage.py -n "__fish_use_subcommand rest_framework" -a "rest_framework"
complete -f -c manage.py -n "__fish_seen_subcommand_from rest_framework" -a "generateschema"

complete -f -c manage.py -n "__fish_use_subcommand sessions" -a "sessions"
complete -f -c manage.py -n "__fish_seen_subcommand_from sessions" -a "clearsessions"

complete -f -c manage.py -n "__fish_use_subcommand staticfiles" -a "staticfiles"
complete -f -c manage.py -n "__fish_seen_subcommand_from staticfiles" -a "collectstatic"
complete -f -c manage.py -n "__fish_seen_subcommand_from staticfiles" -a "findstatic"
complete -f -c manage.py -n "__fish_seen_subcommand_from staticfiles" -a "runserver"
