#! /bin/sh

. "$HOME/.config/bspwm/themes/bsp.cfg"
killall sxhkd; sxhkd &
#nitrogen --restore &
$HOME/.config/i3/monitor/saver.sh &

#bspc monitor eDP1 -n 0 -d 1 2 3 4 5 6 7 8
#bspc monitor HDMI1 -n 1 -d 9 10

#/home/alexvanaxe/.config/i3/conky/conky.sh &

#/home/alexvanaxe/.config/conky/day/conky.sh
#/home/alexvanaxe/.config/conky/tonight/conky.sh
#stalonetray &
killall clipster; clipster -d &

# Configure the window manager
#polybar example &
#bspc monitor -d          X
bspc monitor ^1 -d terminal 
bspc monitor ^2 -d terminal 

# Prevent windows to steal focus
#bspc config ignore_ewmh_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config border_width         1
bspc config window_gap           6
bspc config split_ratio 0.60

# App rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Surf state=tiled
bspc rule -a ffplay state=floating
bspc rule -a Gpick state=floating
bspc rule -a qutebrowser desktop=^2
bspc rule -a mpv desktop=\^5
bspc rule -a Alacritty:vis desktop=^5 state=tiled
bspc rule -a Alacritty:weechat desktop=^7 state=tiled
#bspc rule -a Gnome-calculator state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

