#! /bin/bash

. "$HOME/.config/bspwm/themes/bsp.cfg"
killall sxhkd; sxhkd >>/tmp/sxhkcd.log 2>&1 &
$HOME/.config/i3/monitor/saver.sh &

$HOME/bin/bspwm_layout_manager.sh clear

# Configure the window manager
#polybar example &
bspc monitor ^1 -d terminal
bspc monitor ^2 -d terminal

# Prevent windows to steal focus
#bspc config ignore_ewmh_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config border_width         1
bspc config window_gap           6
bspc config split_ratio 0.60

bspc config pointer_follows_monitor true

# App rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a ffplay state=floating
bspc rule -a Gpick state=floating
bspc rule -a qutebrowser desktop=^2
bspc rule -a mpv state=pseudo_tiled rectangle=1850x1040+0+0
#bspc rule -a mpv desktop=\^5
#bspc rule -a Alacritty:vis desktop=^5 state=tiled
#bspc rule -a Alacritty:weechat desktop=^7 state=tiled
#bspc rule -a Gnome-calculator state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

pid=$(ps aux | egrep "[c]lipster" | awk '{print $2}')

if [ -z ${pid} ]; then
    clipster -d
fi
