#!/usr/bin/env bash

source /home/alexvanaxe/.pyenv/versions/spotify/bin/activate
POMODORO=$(/home/alexvanaxe/.config/i3/scripts/pomodoro-client.py status)

if [ -z "$POMODORO" ]; then
	echo "" || exit 1
elif [[ "$POMODORO" = *"PAUSED"* ]]
then
	echo " $POMODORO" || exit 1
else
	echo " $POMODORO" || exit 1
fi

