# ng help
complete -f -c ng -n "__fish_use_subcommand" -a "add" -d "Adds support for an external library to your project."


complete -x -c ng -n "__fish_seen_subcommand_from add" -a "--defaults"     -d "When true, disables interactive input prompts for options with a default."
complete -x -c ng -n "__fish_seen_subcommand_from add" -a "--help"         -d "Shows a help message for this command in the console."
complete -x -c ng -n "__fish_seen_subcommand_from add" -a "--interactive"  -d "When false, disables interactive input prompts."
complete -x -c ng -n "__fish_seen_subcommand_from add" -a "--registry"     -d "The NPM registry to use."
complete -x -c ng -n "__fish_seen_subcommand_from add" -a "--verbose"      -d "Display additional details about internal operations during execution."

complete -f -c ng -n "__fish_use_subcommand" -a "analytics" -d "Configures the gathering of Angular CLI usage metrics. See https://angular.io/cli/usage-analytics-gathering."
complete -f -c ng -n "__fish_use_subcommand" -a "build" -d "Compiles an Angular app into an output directory named dist/ at the given output path. Must be executed from within a workspace directory."
complete -f -c ng -n "__fish_use_subcommand" -a "deploy" -d "Invokes the deploy builder for a specified project or for the default project in the workspace."
complete -f -c ng -n "__fish_use_subcommand" -a "config" -d "Retrieves or sets Angular configuration values in the angular.json file for the workspace."
complete -f -c ng -n "__fish_use_subcommand" -a "doc" -d "Opens the official Angular documentation (angular.io) in a browser, and searches for a given keyword."
complete -f -c ng -n "__fish_use_subcommand" -a "e2e" -d "Builds and serves an Angular app, then runs end-to-end tests using Protractor."
complete -f -c ng -n "__fish_use_subcommand" -a "generate" -d "(g) Generates and/or modifies files based on a schematic."
complete -f -c ng -n "__fish_use_subcommand" -a "help" -d "Lists available commands and their short descriptions."
complete -f -c ng -n "__fish_use_subcommand" -a "lint" -d "Runs linting tools on Angular app code in a given project folder."
complete -f -c ng -n "__fish_use_subcommand" -a "new" -d "Creates a new workspace and an initial Angular app."
complete -f -c ng -n "__fish_use_subcommand" -a "run" -d "Runs an Architect target with an optional custom builder configuration defined in your project."
complete -f -c ng -n "__fish_use_subcommand" -a "serve" -d "Builds and serves your app, rebuilding on file changes."

complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "project" -d "The name of the project to build. Can be an application or a library."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--allowed-hosts" -d "Whitelist of hosts that are allowed to access the dev server."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--aot" -d "Build using Ahead of Time compilation."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--base-href" -d "Base url for the application being built."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--browser-target" -d "Target to serve."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--build-event-log" -d "**EXPERIMENTAL** Output file path for Build Event Protocol events"
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--common-chunk" -d "Use a separate bundle containing code used across multiple bundles."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--configuration" -d "(-c) A named build target, as specified in the "configurations" section of angular.json.  Each named target is accompanied by a configuration of option defaults for that target.  Setting this explicitly overrides the "--prod" flag"
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--deploy-url" -d "URL where files will be deployed."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--disable-host-check" -d "Don't verify connected clients are part of allowed hosts."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--eval-source-map" -d "Output in-file eval sourcemaps."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--help" -d "Shows a help message for this command in the console."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--hmr" -d "Enable hot module replacement."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--hmr-warning" -d "Show a warning when the --hmr option is enabled."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--host" -d "Host to listen on."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--live-reload" -d "Whether to reload the page on change, using live-reload."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--open" -d "(-o) Opens the url in default browser."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--optimization" -d "Enables optimization of the build output."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--poll" -d "Enable and define the file watching poll time period in milliseconds."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--port" -d "Port to listen on."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--prod" -d "Shorthand for "--configuration=production".  When true, sets the build configuration to the production target.  By default, the production target is set up in the workspace configuration such that all builds make use of bundling, limited tree-shaking, and also limited dead code elimination."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--progress" -d "Log progress to the console while building."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--proxy-config" -d "Proxy configuration file."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--public-host" -d "The URL that the browser client (or live-reload client, if enabled) should use to connect to the development server. Use for a complex dev server setup, such as one with reverse proxies."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--serve-path" -d "The pathname where the app will be served."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--serve-path-default-warning" -d "Show a warning when deploy-url/base-href use unsupported serve path values."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--source-map" -d "Output sourcemaps."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--ssl" -d "Serve using HTTPS."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--ssl-cert" -d "SSL certificate to use for serving HTTPS."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--ssl-key" -d "SSL key to use for serving HTTPS."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--vendor-chunk" -d "Use a separate bundle containing only vendor libraries."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--vendor-source-map" -d "Resolve vendor packages sourcemaps."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--verbose" -d "Adds more details to output logging."
complete -x -c ng -n "__fish_seen_subcommand_from serve" -a "--watch" -d "Rebuild on change."

complete -f -c ng -n "__fish_use_subcommand" -a "test" -d "Runs unit tests in a project."
complete -f -c ng -n "__fish_use_subcommand" -a "update" -d "Updates your application and its dependencies. See https://update.angular.io/"
complete -f -c ng -n "__fish_use_subcommand" -a "version" -d "Outputs Angular CLI version."
complete -f -c ng -n "__fish_use_subcommand" -a "xi18n" -d "Extracts i18n messages from source code."
