#!/bin/sh

case "$1" in
    dual)
	    xrandr --output HDMI2 --off --output HDMI1 --mode 1920x1080 --pos 1440x0 --rotate normal --output DP1 --primary --mode 1440x900 --pos 0x0 --rotate normal --output eDP1 --off --output VIRTUAL1 --off
        ;;
    hdmi)
	    xrandr --output HDMI2 --off --output HDMI1 --mode 1920x1080 --pos 1440x0 --rotate normal --output DP1 --off --output eDP1 --off --output VIRTUAL1 --off
        ;;
    note)
	    xrandr --output HDMI2 --off --output HDMI1 --off --output DP1 --off --output eDP1 --mode 1366x768 --pos 0x0 --rotate normal --output VIRTUAL1 --off
        ;;
    32g)
	    xrandr --output HDMI2 --off --output HDMI1 --mode 1920x1080 --pos 1440x0 --rotate normal --output DP1 --primary --mode 1440x900 --pos 0x0 --rotate normal --output eDP1 --mode 1366x768 --pos 0x1120 --rotate normal --output VIRTUAL1 --off
        ;;
    tubo)
	    xrandr --output HDMI2 --off --output HDMI1 --off --output DP1 --mode 1440x900 --pos 0x0 --rotate normal --output eDP1 --off --output VIRTUAL1 --off
        ;;
    *)
        echo "Usage: $0 {dual|hdmi}"
        exit 2
esac

exit 0

